### ISSUE TITLE
Bot instead of AutoShardedBot

### ISSUE THREAD

**Issue by isik-kaplan** [discord-python/bot#87]
https://github.com/discord-python/bot/blob/16f35b5b81f790224c4b6dfcde8486cd73875266/bot/__main__.py#L14

Why not just `discord.ext.commands.Bot`

**Comment by Volcyy** [comment]
what's wrong with autoshardedbot?

**Comment by JoeBanks13** [comment]
The bot will never be sharded as it will never reach an amount of servers where discord tells it to shard, nothing *wrong* with it, just doesn't need to be used.

**Comment by 1mn** [comment]
yeah, I think this is worth considering doing a PR for. I don't see us ever needing AutoShardedBot.
